### PR TITLE
Use Canvas Instead

### PR DESCRIPTION
**Pull request by noahbuscher**
I migrated everything over to a canvas element, instead of using tons of separate elements for the pixels. Most stuff stayed the same, but the biggest differences are:
- To make a canvas for pixel picker, just use something like `<canvas width="300" height="300" id="pixel-picker"></canvas>`
- Cell data is stored in objects, instead of the 2D array; this way you can see the positions of the cells on the canvas; not totally necessary, but I find it helpful and it saves you from needing to calculate the cell position
- No more CSS file needed
- To specify cell size, just use the `size` param in the settings object
- To specify cell border color, just use the `borderColor` param in the settings object
- Quick example added

And yes, the README is updated and comments are added, in compliance with the existing code style.

### CODE REVIEW

**Comment by jodyheavener** [comment]
_WOW._

Haven't checked out how the code works yet, but overall this is a really fantastic improvement. :clap: for speed as well!

There are, however, are a few things that need to be addressed before we can move forward:
- Need to be able to specify the number of rows, and cells per row, rather than relying on width/height/cell size values. I suppose we could just do some math (i.e. `cellSize * cellsPerRow = canvasWidth` and  `cellSize * rows = canvasHeight` or something), but that adds another layer of unnecessary complexity. I think we could overlook this, though, if we need to.
- Canvas isn't great with responsiveness, which is now a requirement on DN -- I imagine on window resize there will need to be a whole lot of calculations to maintain the square cells, which could be a significant performance hit.
- This one sucks but is necessary for DN specifically: need the output value to be a 2d array :( it's how we convert the data to a .png image.
- Is the eraser working? CMD+clicking doesn't seem to erase for me.

**Comment by noahbuscher** [comment]
Hey, @jodyheavener! Thanks for getting back! I'll answer your questions in order:
- I chose to go with cell size for simplicity's sake, but I'd be more than happy to add the other params into the settings; doing now
- I'll do a bit of checking to see what the best possible method for resizing the canvas is
- Do you want it to only export a 2D array, or should I make a function to convert the object array into a 2D array? Both are totally doable
- The eraser is not working :open_mouth: fixing now!

**Comment by jodyheavener** [comment]
@noahbuscher :smile: 

> I chose to go with cell size for simplicity's sake

If you haven't already updated it, don't worry about it. Let's see how it works as is!

> Do you want it to only export a 2D array, or should I make a function to convert the object array into a 2D array?

May as well leave it how you have it, but add option to convert. I'm not sure what other applications this plugin will have aside from DN, so I'm not sure what the best data format would be.

**Comment by noahbuscher** [comment]
@jodyheavener So - I added the export to a 2D array. The update param now only returns a mapped 2D array of pixels, as before. Eg: `map[row][cell]` would return an array like `[255, 0, 0]`, if the cell was white.

The main difference, though, is that is creates this array on the fly. I am doing this, as otherwise when you clicked or hovered over a cell, it would need do compute a good deal of math in order to triangulate which cell to edit, as it only would have the mouse position, height/width of the cell, and size of the canvas to work with, which is enough data, but it might take more time to export.

Going to also write some code to just work with a 2D array (instead of mapping on the fly) to see if there is a performance boost/hit. That way we can choose the fastest method, as processors on mobile devices, though powerful, might not like it.

**Comment by noahbuscher** [comment]
@jodyheavener after some review, it appears that the second option (using 2D arrays for everything) may not the be the best idea. This is because there is quite a bit of approximation as to where the mouse cursor is (with the method I am trying, which is the only solution for this afaik), and it's not super resilient. It takes `14ms` to calculate and return an array of 400 squares, so it's not a huge performance hit. I can work on it more in the coming days.

**Comment by jodyheavener** [comment]
This looks like it's coming along great! Just ping the thread when you've had a chance to look at resizing the cells (if it's do-able) :)

**Comment by noahbuscher** [comment]
@jodyheavener Awesome! I'm getting close on the responsive canvas; trying to find the most efficient solution.

**Comment by noahbuscher** [comment]
@jodyheavener Totally spaced this off! I was super busy; hopefully I'll be able to wrap this bad boy up this weekend. :+1:

**Pull request closed without merging**
